# Site settings
author: Elise Phan
title: My Blog
header-img: img/home-bg.png
email: aliceconnic@gmail.com
copyright_name: Elise Phan
description: > # this means to ignore newlines until "baseurl:"
  This is where I post my coding experience
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  eliphan

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
